# Generated by Django 4.2.25 on 2025-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('enable_nutrition', models.BooleanField(default=False, help_text='Show and use extended nutrition fields (carbs, protein, etc.).')),
                ('enable_vegan_flags', models.BooleanField(default=True, help_text='Show vegan/vegetarian markers on dishes.')),
                ('enable_product_fields', models.BooleanField(default=False, help_text='Show supplier / barcode / external product fields on dishes.')),
                ('enable_audit_log', models.BooleanField(default=True, help_text='Require change reasons and record dish change history.')),
            ],
            options={
                'verbose_name': 'App settings',
                'verbose_name_plural': 'App settings',
            },
        ),
    ]
