# Generated by Django 4.2.25 on 2025-10-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('cat_image', models.URLField(blank=True, default='https://i.ibb.co/7QpKsCX/white-background.jpg')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('logo', models.URLField(blank=True, default='https://i.ibb.co/7QpKsCX/white-background.jpg')),
                ('background_image', models.URLField(blank=True, default='https://i.ibb.co/7QpKsCX/white-background.jpg')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('subcat_image', models.URLField(blank=True, default='https://i.ibb.co/7QpKsCX/white-background.jpg')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.category')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, default='https://i.ibb.co/7QpKsCX/white-background.jpg')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archive', 'Archive')], default='inactive', max_length=10)),
                ('kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('allergens', models.ManyToManyField(blank=True, to='menus.allergen')),
                ('category', models.ManyToManyField(related_name='dishes_in_category', to='menus.category')),
                ('menu_type', models.ManyToManyField(related_name='dishes_on_menu', to='menus.menu_type')),
                ('subcategory', models.ManyToManyField(blank=True, related_name='dishes_in_subcategory', to='menus.subcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
