# Generated by Django 4.2.25 on 2025-10-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='menu_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menus.menu_type'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='menus.category'),
        ),
    ]
