# Generated by Django 4.2.25 on 2025-10-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_remove_dish_subcategory_category_menu_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes_in_sub', to='menus.subcategory'),
        ),
    ]
