# Generated by Django 4.2.25 on 2025-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menu_type',
            name='accent_color',
            field=models.CharField(default='#eab308', help_text='Hex colour for buttons/highlights', max_length=7),
        ),
        migrations.AddField(
            model_name='menu_type',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Hex colour for page background', max_length=7),
        ),
        migrations.AddField(
            model_name='menu_type',
            name='font_family',
            field=models.CharField(default="system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", help_text='CSS font-family stack', max_length=200),
        ),
        migrations.AddField(
            model_name='menu_type',
            name='primary_color',
            field=models.CharField(default='#0f172a', help_text='Hex colour, e.g. #0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='menu_type',
            name='secondary_color',
            field=models.CharField(default='#1e293b', help_text='Hex colour, e.g. #1e293b', max_length=7),
        ),
        migrations.AddField(
            model_name='menu_type',
            name='text_color',
            field=models.CharField(default='#0f172a', help_text='Hex colour for main text', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
