# Generated by Django 4.2.25 on 2025-12-08 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0005_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='edit_lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='external_product_url',
            field=models.URLField(blank=True, help_text='Link to supplier or spec sheet'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='last_change_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dish',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_dishes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='product_barcode',
            field=models.CharField(blank=True, help_text='EAN/UPC if available', max_length=32),
        ),
        migrations.AddField(
            model_name='dish',
            name='supplier_code',
            field=models.CharField(blank=True, help_text='Internal code or PLU', max_length=50),
        ),
        migrations.AddField(
            model_name='dish',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='DishNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('carbs', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('sugar', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('fibre', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('salt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('portion_size', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='menus.dish')),
            ],
            options={
                'verbose_name': 'Dish nutrition',
                'verbose_name_plural': 'Dish nutrition',
            },
        ),
        migrations.CreateModel(
            name='DishChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_change_logs', to=settings.AUTH_USER_MODEL)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='menus.dish')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
